import { useEffect } from 'react'
import TickerTape from '../components/layout/TickerTape'
import Navigation from '../components/layout/Navigation'
import Footer from '../components/layout/Footer'
import SectionLabel from '../components/shared/SectionLabel'

export default function Disclaimer() {
  useEffect(() => {
    document.title = 'Maddex — Disclaimer'
  }, [])

  return (
    <>
      <TickerTape />
      <Navigation />

      <section className="bg-bg-primary pt-[84px] pb-16 px-6 md:px-10 text-center">
        <SectionLabel center>LEGAL</SectionLabel>
        <h1 className="font-sans text-[36px] md:text-[56px] font-bold leading-tight tracking-tight text-text-primary max-w-3xl mx-auto">
          General Information Disclaimer
        </h1>
        <p className="font-mono text-[11px] text-text-faint mt-4">Last updated: August 2026</p>
      </section>

      <section className="bg-bg-surface py-14 px-6 md:px-10">
        <div className="max-w-[760px] mx-auto flex flex-col gap-7">
          <div>
            <h2 className="font-sans text-[19px] font-bold text-gold">General information only</h2>
            <p className="font-sans text-[15px] text-text-muted mt-3 leading-[1.8]">
              Maddex, MaddenAI, MaddenAI Research Notes, and the MaddenAI Newsletter provide general
              financial information only. Nothing on this platform constitutes financial product advice, a
              personal recommendation, or an offer or solicitation to buy or sell any financial product. The
              information provided does not take into account your objectives, financial situation, or needs.
            </p>
          </div>
          <div>
            <h2 className="font-sans text-[19px] font-bold text-gold">Seek independent advice</h2>
            <p className="font-sans text-[15px] text-text-muted mt-3 leading-[1.8]">
              Before acting on any information provided by Maddex, you should consider its appropriateness
              having regard to your own objectives, financial situation, and needs, and consider seeking
              independent financial, legal, or taxation advice from a licensed professional.
            </p>
          </div>
          <div>
            <h2 className="font-sans text-[19px] font-bold text-gold">AI-generated analysis</h2>
            <p className="font-sans text-[15px] text-text-muted mt-3 leading-[1.8]">
              MaddenAI scores, sentiment readings, and analysis are generated by automated models processing
              publicly available and licensed data. They are illustrative and may be incomplete, delayed, or
              inaccurate, and should never be treated as a substitute for professional financial advice.
            </p>
          </div>
          <div>
            <h2 className="font-sans text-[19px] font-bold text-gold">Past performance</h2>
            <p className="font-sans text-[15px] text-text-muted mt-3 leading-[1.8]">
              Past performance is not indicative of future results. All investments carry risk, including the
              risk of loss of capital.
            </p>
          </div>
          <div>
            <h2 className="font-sans text-[19px] font-bold text-gold">Market data</h2>
            <p className="font-sans text-[15px] text-text-muted mt-3 leading-[1.8]">
              Market data displayed within Maddex is sourced from third-party providers and may be delayed,
              incomplete, or subject to correction. Maddex does not warrant the accuracy or completeness of
              any data displayed on the platform.
            </p>
          </div>
          <div>
            <h2 className="font-sans text-[19px] font-bold text-gold">Contact</h2>
            <p className="font-sans text-[15px] text-text-muted mt-3 leading-[1.8]">
              Questions about this disclaimer can be sent to hello@maddex.com.au.
            </p>
          </div>
        </div>
      </section>

      <Footer />
    </>
  )
}
