import { useEffect } from 'react'
import TickerTape from '../components/layout/TickerTape'
import Navigation from '../components/layout/Navigation'
import Footer from '../components/layout/Footer'
import SectionLabel from '../components/shared/SectionLabel'

const SECTIONS = [
  {
    title: '1. Who we are',
    body: 'Maddex is operated by Madden Group Holdings Pty Ltd (ABN [XX XXX XXX XXX]), an Australian company. This policy explains how we collect, use, store, and protect your personal information when you use the Maddex website and the Maddex Terminal.',
  },
  {
    title: '2. Information we collect',
    body: 'We collect information you provide directly — such as your name, email address, and account preferences when you sign up — and information generated by your use of the service, such as your watchlist, portfolio holdings, and settings. We do not collect more than is reasonably necessary to provide the service.',
  },
  {
    title: '3. How we use your information',
    body: 'We use your information to operate and improve the Maddex Terminal, to communicate with you about your account and product updates you have opted into, and to comply with our legal obligations. We do not sell your personal information to third parties.',
  },
  {
    title: '4. Data storage and security',
    body: 'Account and application data is stored with Supabase using industry-standard encryption in transit and at rest. Access to production data is restricted to what is required to operate and support the service.',
  },
  {
    title: '5. Third-party services',
    body: 'Maddex relies on third-party providers for authentication, hosting, and market data (including but not limited to Supabase, Vercel, and financial data vendors). These providers process data on our behalf under their own privacy and security commitments.',
  },
  {
    title: '6. Your rights',
    body: 'You can access, correct, or request deletion of your personal information at any time from your account settings, or by contacting us directly. You may also opt out of non-essential email communications at any time.',
  },
  {
    title: '7. Cookies',
    body: 'We use essential cookies and local storage to keep you signed in and to remember your preferences. We do not use third-party advertising trackers.',
  },
  {
    title: '8. Changes to this policy',
    body: 'We may update this policy from time to time. Material changes will be notified via the website or by email where appropriate.',
  },
  {
    title: '9. Contact',
    body: 'Questions about this policy can be sent to hello@maddex.com.au.',
  },
]

export default function Privacy() {
  useEffect(() => {
    document.title = 'Maddex — Privacy Policy'
  }, [])

  return (
    <>
      <TickerTape />
      <Navigation />

      <section className="bg-bg-primary pt-[84px] pb-16 px-6 md:px-10 text-center">
        <SectionLabel center>LEGAL</SectionLabel>
        <h1 className="font-sans text-[36px] md:text-[56px] font-extrabold leading-tight tracking-[-0.03em] text-text-primary max-w-3xl mx-auto">
          Privacy Policy
        </h1>
        <p className="font-mono text-[11px] text-text-faint mt-4">Last updated: August 2026</p>
      </section>

      <section className="bg-bg-surface py-24 px-6 md:px-10">
        <div className="max-w-[760px] mx-auto flex flex-col gap-7">
          {SECTIONS.map((s) => (
            <div key={s.title}>
              <h2 className="font-sans text-[19px] font-bold text-gold">{s.title}</h2>
              <p className="font-sans text-[15px] text-text-muted mt-3 leading-[1.8]">{s.body}</p>
            </div>
          ))}
        </div>
      </section>

      <Footer />
    </>
  )
}
